export type Language = "en" | "de";
export type OrderStatus = "New" | "In progress" | "Review" | "Ready";
export type StatusFilter = "All" | OrderStatus;

export const statuses: StatusFilter[] = ["All", "New", "In progress", "Review", "Ready"];
export const flowStages: OrderStatus[] = ["New", "In progress", "Review", "Ready"];

export const copy = {
  en: {
    languageButton: "DE",
    languageButtonLabel: "Website auf Deutsch anzeigen",
    homeLabel: "Klarlauf home",
    systemLabel: "Studio operations / desk 01",
    ordersTitle: "Orders",
    active: "Active",
    pipeline: "Pipeline",
    createNew: "Create new order",
    stagesLabel: "Order stages",
    order: "order",
    orders: "orders",
    liveQueue: "Live queue",
    queueTitle: "Orders in motion",
    searchLabel: "Search orders",
    searchPlaceholder: "Client, project or ID",
    filtersLabel: "Filter orders by status",
    status: { All: "All", New: "New", "In progress": "In progress", Review: "Review", Ready: "Ready" },
    loadingOrders: "Loading orders from the database…",
    noResults: (query: string) => `No orders found for “${query}”.`,
    noOrders: "No orders match this view.",
    clientOrder: "Client order",
    dueDate: "Due date",
    orderValue: "Order value",
    openOrder: "Open order",
    progress: "progress",
    closeCreate: "Close create-order form",
    closeEdit: "Close edit-order form",
    closeForm: "Close form",
    newEntry: "New entry",
    createOrder: "Create order",
    editOrder: "Edit order",
    client: "Client",
    project: "Project",
    clientPlaceholder: "e.g. Maya Chen",
    projectPlaceholder: "e.g. Landing page refresh",
    statusLabel: "Status",
    cancel: "Cancel",
    saving: "Saving…",
    addToQueue: "Add to queue",
    deleteOrder: "Delete order",
    saveChanges: "Save changes",
    confirmDelete: (id: string, client: string) => `Delete ${id} for ${client}?`,
    errors: {
      load: "Could not load orders.",
      createFields: "Complete every field and enter a value above €0.",
      create: "Could not create the order.",
      updateFields: "Complete every field and choose a valid status.",
      update: "Could not update the order.",
      remove: "Could not delete the order.",
    },
  },
  de: {
    languageButton: "EN",
    languageButtonLabel: "Show website in English",
    homeLabel: "Klarlauf Startseite",
    systemLabel: "Studioabläufe / Platz 01",
    ordersTitle: "Aufträge",
    active: "Aktiv",
    pipeline: "Auftragswert",
    createNew: "Neuen Auftrag anlegen",
    stagesLabel: "Auftragsphasen",
    order: "Auftrag",
    orders: "Aufträge",
    liveQueue: "Aktuelle Übersicht",
    queueTitle: "Aufträge in Bewegung",
    searchLabel: "Aufträge durchsuchen",
    searchPlaceholder: "Kunde, Projekt oder ID",
    filtersLabel: "Aufträge nach Status filtern",
    status: { All: "Alle", New: "Neu", "In progress": "In Arbeit", Review: "Prüfung", Ready: "Bereit" },
    loadingOrders: "Aufträge werden aus der Datenbank geladen…",
    noResults: (query: string) => `Keine Aufträge für „${query}“ gefunden.`,
    noOrders: "Keine Aufträge entsprechen dieser Ansicht.",
    clientOrder: "Kundenauftrag",
    dueDate: "Fällig am",
    orderValue: "Auftragswert",
    openOrder: "Auftrag öffnen",
    progress: "Fortschritt",
    closeCreate: "Formular zum Anlegen eines Auftrags schließen",
    closeEdit: "Formular zum Bearbeiten eines Auftrags schließen",
    closeForm: "Formular schließen",
    newEntry: "Neuer Eintrag",
    createOrder: "Auftrag anlegen",
    editOrder: "Auftrag bearbeiten",
    client: "Kunde",
    project: "Projekt",
    clientPlaceholder: "z. B. Maya Chen",
    projectPlaceholder: "z. B. Landingpage überarbeiten",
    statusLabel: "Status",
    cancel: "Abbrechen",
    saving: "Wird gespeichert…",
    addToQueue: "Zur Übersicht hinzufügen",
    deleteOrder: "Auftrag löschen",
    saveChanges: "Änderungen speichern",
    confirmDelete: (id: string, client: string) => `${id} für ${client} löschen?`,
    errors: {
      load: "Aufträge konnten nicht geladen werden.",
      createFields: "Füllen Sie alle Felder aus und geben Sie einen Wert über 0 € ein.",
      create: "Der Auftrag konnte nicht angelegt werden.",
      updateFields: "Füllen Sie alle Felder aus und wählen Sie einen gültigen Status.",
      update: "Der Auftrag konnte nicht aktualisiert werden.",
      remove: "Der Auftrag konnte nicht gelöscht werden.",
    },
  },
} as const;
